cyclomatic_complexity:
  warning: 25
  error: 30

type_body_length:
  warning: 500
  error: 700

file_length:
  warning: 1000
  error: 1300

line_length:
  ignores_comments: true
  warning: 200
  error: 300

large_tuple: 
  warning: 4

type_name:
  min_length: 2
  max_length:
    warning: 50
    error: 60
  excluded:
    - Id
    - Ad

identifier_name:
  excluded:
    - id
    - kp

function_body_length:
  warning: 120
  error: 150

function_parameter_count:
  warning: 7
  error: 10

nesting:
  type_level:
    warning: 10
    error: 15
disabled_rules:
  - opening_brace
  - first_where
  - object_literal
  - trailing_whitespace
  - notification_center_detachment
# Временное выключение из-за https://github.com/realm/SwiftLint/issues/1573
  - vertical_parameter_alignment_on_call
  - vertical_parameter_alignment
